paths:
    path_to_data : Path(PATH_TO_DATA) #../data/
    path_to_artifacts : Path(PATH_ARTIFACTS) #../artifacts/
    
    path_to_conso : path_to_data / "conso/"
    path_to_clean_conso : path_to_conso / "clean_conso/"
    path_to_calendar : path_to_data / "calendar/"
    path_to_py_artifacts : path_to_artifacts / "py_artifacts/"
    path_to_weather : path_to_data / "weather/"
    path_to_clean_weather : path_to_weather / "clean_weather/"
    
    path_to_final_datasets : path_to_data / "final_datasets/"
    path_to_datasets_versions : path_to_final_datasets / "datasets_versions/"
files:
  train_dataset: "data/processed/train.parquet"
  test_dataset: "data/processed/test.parquet"